apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ok8u97q1h-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ok8u97q1h-java-springboot-gitops